#!/usr/bin/perl
# look for the markers provided by Mathieu in the new genomes
# GNA Gina Cannarozzi Nov 20 2018
# markers look like this Peaxi162Scf00207_1147515
# the first line of the input file is a list of markers separated by commas

use warnings;
use strict;

open my $file, '<', "F7_V3.allmarkers.map.csv" || die "can not open file" ;

my $firstline = <$file>; 
close $file;

my @words = split /,/, $firstline;
shift @words;   # remove the first member of the list which is a row heading
#print "\n";
print "#!/bin/sh \n"; 
print "# processing " . scalar(@words) . " files\n"; 
print "# this script is automatically generated by the perl script extract.pl \n"; 
#print "\n";

foreach my $name (@words) {
  if ($name =~ /Peax/) {
    my @marker = split /_/, $name;
    my $scaf = $marker[0]; 
    my $pos = $marker[1]; 
    my $up = $pos + 100; 
    my $down = $pos - 100; if ($down <= 0) {$down = 1};
#    print $scaf, "\t", $pos, "\n";
    print "seqret /home/cannarozzi/petunia/genomes/paxillaris/Peaxil162/Peaxi_genome_v1.6.2.scaffolds.fasta:" . $scaf . " -sbegin=" . $down . " -send=" . $up . " -auto -outseq 162seqs/"  . $name . ".fasta" . "\n";  
  };
};
